[output.html.fold]
enable = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[TOC]"

[preprocessor.graph]
command = "python preprocessor.py"

[output.html]
default-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]